name: BUILD PKGBUILD
on: 
  workflow_dispatch:

  workflow_run:
    workflows: ['Update checksums']
    types:
      - completed

jobs:
  build_with_llvm_lto:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Extract PKGBUILD Version
      id: extract_pkgver
      run: |
        PKGBUILD_PATH="PKGBUILD"
        _major=$(grep -Po '^_major=\K.*' $PKGBUILD_PATH)
        _minor=$(grep -Po '^_minor=\K.*' $PKGBUILD_PATH)
        PKGVER="${_major}.${_minor}"
        echo "Package version extracted from PKGBUILD: $PKGVER"
        echo "::set-output name=pkgver::$PKGVER"
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "workflow"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
          allowUpdates: true
          tag: ${{ format('{0}-llvm-lto-x86-64-v2', steps.extract_pkgver.outputs.pkgver) }}
          commit: main
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
