name: BUILD PKGBUILD
on: 
  workflow_run:
    workflows: ['Update checksums']
    types:
      - completed

#  workflow_dispatch: # uncomment & comment out if condition below for manual trigger

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true


  build_with_llvm_lto:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Extract PKGBUILD Version
      id: extract_pkgver
      run: |
        PKGBUILD_PATH="PKGBUILD"
        _major=$(grep -Po '^_major=\K.*' $PKGBUILD_PATH)
        _minor=$(grep -Po '^_minor=\K.*' $PKGBUILD_PATH)
        PKGVER="${_major}.${_minor}"
        echo "Package version extracted from PKGBUILD: $PKGVER"
        echo "::set-output name=pkgver::$PKGVER"
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1.1.8
      with:
          pkgdir: "workflow"
          namcapDisable: 1
          makepkgArgs: "--skippgpcheck --noconfirm -s"
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
          allowUpdates: true
          tag: ${{ format('{0}-llvm-lto-x86-64-v2', steps.extract_pkgver.outputs.pkgver) }}
          commit: main
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
