name: Update checksums

#on:
#  push:
#    branches: main
on: 
  workflow_run:
    workflows: ['Auto update Kernel Version']
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update PKGBUILD'  # Skip if commit is made by workflow itself
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate package
        uses: MotorTruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          flags: ''
          namcap: false
          updpkgsums: true

      - name: Copy processed PKGBUILD to target directory in main repo
        run: |
          mkdir -p $GITHUB_WORKSPACE/processed
          cp $GITHUB_WORKSPACE/PKGBUILD $GITHUB_WORKSPACE/processed/
          
      - name: Download pkgrel update artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: new-kernel
          run-id: ${{ github.event.workflow_run.id }}
          path: ./

      - name: Conditionally bump pkgrel for both PKGBUILD files
        run: |
          # If the artifact is missing, bump pkgrel
          if [[ ! -f "new-release-update.txt" ]]; then

              # Bump pkgrel for the main PKGBUILD
              current_pkgrel_main=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
              next_pkgrel_main=$((current_pkgrel_main + 1))
              sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_main/" PKGBUILD

              # Bump pkgrel for the processed PKGBUILD
              current_pkgrel_processed=$(grep '^pkgrel=' $GITHUB_WORKSPACE/processed/PKGBUILD | cut -d'=' -f2)
              next_pkgrel_processed=$((current_pkgrel_processed + 1))
              sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_processed/" $GITHUB_WORKSPACE/processed/PKGBUILD
              echo "Auto bump pkgrel"
          else
              echo "new-release-update.txt found. Skipping bump."
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add $GITHUB_WORKSPACE/processed/PKGBUILD PKGBUILD
          git commit -m "Update PKGBUILD"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

