name: Update checksums

#on:
#  push:
#    branches: main
on: 
  workflow_run:
    workflows: ['Auto update Kernel Version']
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update PKGBUILD'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate package
        uses: MotorTruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          flags: ''
          namcap: false
          updpkgsums: true

      - name: Download pkgrel update artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: new-kernel
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Check for material changes between processed and root PKGBUILD
        id: check_changes
        run: |
          # Ensure /processed/PKGBUILD exists
          if [ ! -f processed/PKGBUILD ]; then
            echo "Processed PKGBUILD does not exist. Exiting."
            exit 1
          fi

          # Compare the two files
          if diff -q PKGBUILD processed/PKGBUILD > /dev/null; then
            echo "No material changes between PKGBUILD and processed/PKGBUILD."
            echo "should_bump=false" >> $GITHUB_ENV
          else
            echo "Material changes detected between PKGBUILD and processed/PKGBUILD."
            echo "should_bump=true" >> $GITHUB_ENV
          fi

      - name: Copy processed PKGBUILD to target directory in main repo
        if: env.should_bump == 'true'
        run: |
          mkdir -p $GITHUB_WORKSPACE/processed
          cp $GITHUB_WORKSPACE/PKGBUILD $GITHUB_WORKSPACE/processed/

      - name: Conditionally bump pkgrel for PKGBUILD
        if: env.should_bump == 'true'
        run: |
          current_pkgrel=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
          next_pkgrel=$((current_pkgrel + 1))
          sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel/" PKGBUILD

          current_pkgrel_processed=$(grep '^pkgrel=' processed/PKGBUILD | cut -d'=' -f2)
          next_pkgrel_processed=$((current_pkgrel_processed + 1))
          sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_processed/" processed/PKGBUILD
          echo "Auto bumped pkgrel."

      - name: Commit and push changes
        if: env.should_bump == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add $GITHUB_WORKSPACE/processed/PKGBUILD PKGBUILD
          git commit -m "Update PKGBUILD"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

