name: Update checksums

#on:
#  push:
#    branches: main
on: 
  workflow_run:
    workflows: ['Auto update Kernel Version']
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update PKGBUILD'  # Skip if commit is made by workflow itself
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate package
        uses: MotorTruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          flags: ''
          namcap: false
          updpkgsums: true

      - name: Copy processed PKGBUILD to target directory in main repo
        run: |
          mkdir -p $GITHUB_WORKSPACE/processed
          cp $GITHUB_WORKSPACE/PKGBUILD $GITHUB_WORKSPACE/processed/
          
      - name: Download pkgrel update artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: new-kernel
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Decide whether to bump pkgrel for PKGBUILD
        id: check_changes
        run: |
	    # Do a compare against the latest committed state
	    git fetch origin main
	    git diff origin/main -- PKGBUILD > diff_output.txt

	    if [[ -s diff_output.txt ]]; then
	      echo "Changes detected in PKGBUILD."
	      echo "should_bump=true" >> $GITHUB_ENV
	    else
	      echo "No material changes to PKGBUILD. Exiting."
	      echo "should_bump=false" >> $GITHUB_ENV
	    fi
      - name: Bump pkgrel for new build
        if: env.should_bump == 'true' && !hashFiles('new-release-update.txt')
        run: |
          # Bump pkgrel for the main PKGBUILD
          current_pkgrel=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
          next_pkgrel=$((current_pkgrel + 1))
          sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel/" PKGBUILD

          # Bump pkgrel for the processed PKGBUILD
          current_pkgrel_processed=$(grep '^pkgrel=' $GITHUB_WORKSPACE/processed/PKGBUILD | cut -d'=' -f2)
          next_pkgrel_processed=$((current_pkgrel_processed + 1))
          sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_processed/" $GITHUB_WORKSPACE/processed/PKGBUILD
          echo "Auto bump pkgrel"

      - name: Commit and push changes
        if: env.should_bump == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add $GITHUB_WORKSPACE/processed/PKGBUILD PKGBUILD
          git commit -m "Update PKGBUILD"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

