name: Update checksums

#on:
#  push:
#    branches: main
on: 
  workflow_run:
    workflows: ['Auto update Kernel Version']
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update PKGBUILD'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate package
        uses: MotorTruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          flags: ''
          namcap: false
          updpkgsums: true

      - name: Download pkgrel update artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: new-kernel
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Check if update is necessary
        id: check_changes
        run: |
          # Ensure /processed/PKGBUILD exists
          if [ ! -f processed/PKGBUILD ]; then
            echo "Processed PKGBUILD does not exist. Exiting."
            exit 1
          fi

          # Compare the two files
          if diff -q PKGBUILD processed/PKGBUILD > /dev/null; then
            echo "No changes to be made!"
            echo "push_changes=false" >> $GITHUB_ENV
          else
            echo "New changes detected. Pushing for new build!"
            echo "push_changes=true" >> $GITHUB_ENV
          fi

      - name: Conditionally bump pkgrel for PKGBUILD
        run: |
          # Check if new kernel artifact exists
          if [[ ! -f "new-release-update.txt" ]]; then
              echo "Artifact missing. Checking for changes..."
              if [[ $push_changes == "true" ]]; then
                  # Bump pkgrel for the root PKGBUILD
                  current_pkgrel=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
                  next_pkgrel=$((current_pkgrel + 1))
                  sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel/" PKGBUILD

                  # Bump pkgrel for the processed PKGBUILD
                  current_pkgrel_processed=$(grep '^pkgrel=' processed/PKGBUILD | cut -d'=' -f2)
                  next_pkgrel_processed=$((current_pkgrel_processed + 1))
                  sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_processed/" processed/PKGBUILD
                  echo "Auto bumped pkgrel."
              else
                  echo "Exiting without bumping pkgrel."
                  exit 0
              fi
          else
              echo "Artifact found. Skipping pkgrel bump."
          fi

      - name: Commit and push changes
        if: env.push_changes == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add $GITHUB_WORKSPACE/processed/PKGBUILD PKGBUILD
          git commit -m "Update PKGBUILD"
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
