name: Update checksums

#on:
#  push:
#    branches: main
on:
  workflow_run:
    workflows: ['Auto update Kernel Version']
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update PKGBUILD'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Keep PKGBUILD for processing based on updpkgsums result
        run: |
          mkdir -p original
          cp PKGBUILD original/PKGBUILD

      - name: Validate package
        uses: docker://ghcr.io/rhee876527/archlinux-package-action:edge
        with:
          flags: ''
          namcap: false
          updpkgsums: true

      - name: Debug diff
        run: |
          diff -u original/PKGBUILD PKGBUILD


      - name: Drop pipeline if only archlinux config has changed
        run: |
          # Check for last-source-only checksum update and fail if detected
          diff_output=$(diff -u original/PKGBUILD PKGBUILD)

          awk_program='
          # Count only real diff +/- lines
          /^[+-][^+-]/ { total_changes++ }

          /^         '\''/ || /^[+-][^+-]        '\''/ {
              if (!in_b2sums_hunk) {
                  in_b2sums_hunk = 1;
                  minus_count = 0;
                  plus_count = 0;
                  last_minus = ""
              }
          }
          in_b2sums_hunk && /^-[^-]/ {
              minus_count++;
              last_minus = $0
          }
          in_b2sums_hunk && /^\+[^+]/ {
              plus_count++
          }
          /^@@/ || /diff --git/ {
              if (in_b2sums_hunk && minus_count == 1 && plus_count == 1 && last_minus ~ /\)$/ && total_changes == 2) {
                  exit 1
              }
              in_b2sums_hunk = 0
          }
          END {
              if (in_b2sums_hunk && minus_count == 1 && plus_count == 1 && last_minus ~ /\)$/ && total_changes == 2) {
                  exit 1
              }
          }
          '
          echo "$diff_output" | awk "$awk_program"
          if [ ${PIPESTATUS[1]} -ne 0 ]; then exit 1; fi

          echo "Relevant changes detected. Proceeding with pipeline."

      - name: Download pkgrel update artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: new-kernel
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./

      - name: Check if updpkgsums has triggered change
        run: |
          if diff -q PKGBUILD processed/PKGBUILD > /dev/null; then
            echo "No changes to be made!"
          else
            echo "New changes detected. Pushing for new build!"
            echo "push_changes=true" >> $GITHUB_ENV
          fi

      - name: Decision to bump pkgrel for PKGBUILD
        run: |
          # Check if new kernel artifact exists
          if [[ ! -f "new-release-update.txt" ]]; then
              echo "Artifact missing. Checking for changes..."
              if [[ $push_changes == "true" ]]; then
                  # Bump pkgrel for the root PKGBUILD
                  current_pkgrel=$(grep '^pkgrel=' PKGBUILD | cut -d'=' -f2)
                  next_pkgrel=$((current_pkgrel + 1))
                  sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel/" PKGBUILD

                  # Bump pkgrel for the processed PKGBUILD
                  current_pkgrel_processed=$(grep '^pkgrel=' processed/PKGBUILD | cut -d'=' -f2)
                  next_pkgrel_processed=$((current_pkgrel_processed + 1))
                  sed -i "s/^pkgrel=.*/pkgrel=$next_pkgrel_processed/" processed/PKGBUILD

                  echo "Auto bumped pkgrel!"
              else
                  echo "Bumping pkgrel not needed."
                  exit 0
              fi
          else
              echo "Artifact found. Skipping pkgrel bump."
          fi

      - name: Commit and push changes
        if: env.push_changes == 'true'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          cp $GITHUB_WORKSPACE/PKGBUILD $GITHUB_WORKSPACE/processed/
          git add $GITHUB_WORKSPACE/processed/PKGBUILD PKGBUILD
          git commit -m "Update PKGBUILD"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
