name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: MotorTruck1221/arch-linux-pkgbuild-package@v2.2.1
        with:
          flags: ''
          namcap: false
          updpkgsums: true

